on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: multiple command in PROD server
        uses: appleboy/ssh-action@master
        with:
          host: 31.129.96.24
          username: ${{ secrets.ssh_username }}
          password: ${{ secrets.ssh_password }}
          script: >-
            cd /home/server/birqsil &&
            git pull &&
            composer install &&
            php yii migrate --interactive=0 &&
            chmod u+x ./init.sh &&
            ./init.sh
